### ISSUE TITLE
[Bug] Trade window

### ISSUE THREAD

**Issue by Ben-Judah** [Exkywor/Pokemanki#5]
Hello Exkywor!

I've found this error that unables me to open the trade window. Here's the debug info:

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-05 19:56:46

Caught exception:
Traceback (most recent call last):
  File "C:\Users\Ben-Judah\AppData\Roaming\Anki2\addons21\pokemanki\trades.py", line 33, in open
    self._setup_web_view()
  File "C:\Users\Ben-Judah\AppData\Roaming\Anki2\addons21\pokemanki\trades.py", line 71, in _setup_web_view
    body=self._trades_html(),
  File "C:\Users\Ben-Judah\AppData\Roaming\Anki2\addons21\pokemanki\trades.py", line 333, in _trades_html
    txt += self._trade_html(i)
  File "C:\Users\Ben-Judah\AppData\Roaming\Anki2\addons21\pokemanki\trades.py", line 370, in _trade_html
    f'<span class="pk-td-offer-txt-name"><b>{self.trades[i][0][0]}</b></span>' \
IndexError: list index out of range

Regards

**Comment by Exkywor** [comment]
Could you try replacing Trades.py on your addon folder with this one:
[https://github.com/Exkywor/Pokemanki/blob/beta/trades.py](https://github.com/Exkywor/Pokemanki/blob/beta/trades.py)

It will throw an error when opening the Trades window, so please send me the information at the bottom of it.

**Comment by Ben-Judah** [comment]
So today the trade window worked actually, I think it's an intermittent error.

When I replaced the trades.py with the beta you shared, the trade window still worked, but this debug info appeared:

Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-05 19:56:46

[[['Bidoof', 'F', 0, 15], ['Mankey', 'E', 0, 28]], [['Seismitoad', 'D', 36, 100], ['Lapras', 'C', 0, 100]], [['Staravia', 'F', 14, 34], ['Basculin-Red', 'E', 0, 100]]]

I'll get back to you when the trade window doesn't appear again, and send you the debug info with the beta version

**Comment by Exkywor** [comment]
Please do, I believe it happens when there are no available trades
